volumes:
  volume_name:                                 # <- Rename "volume_name"
    name: pgres
services:
  #run text file that instantiates images
  postgres:
    image: postgres
    ports:
      - "5433:5432" #default numbers
    container_name: postgres-single
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - ./data/order:/var/lib/postgresql/data
      - ./init/order/init.sql:/docker-entrypoint-initdb.d/init.sql
#docker-compose -p postgres-inventory-single -f docker-compose-multiple.yml up -d
    #no network bc local
 #GUI
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    container_name: pgadmin-inventory
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.ca
      - PGADMIN_DEFAULT_PASSWORD=password